### ISSUE TITLE
Suggestion: Windows Installation location

### ISSUE THREAD

**Issue by matthewjnield** [surrealdb/windows.surrealdb.com#3]
### Is your feature request related to a problem?

The SurrealDB installation script for Windows (https://windows.surrealdb.com) first tries to install SurrealDB at `C:\Program Files\SurrealDB` (The conventional location to install programs available to all users on a computer for Windows) which will only work if the installation was run with administrator privileges.

If this fails, the script instead installs SurrealDB in a location that the current user has privileges to write to, currently the `$HOME` directory. This directory is not conventionally used for program installation on Windows; the conventional location for installing programs for a only a given user is `C:\Users\{username}\AppData\Local`.

### Describe the solution

Change the backup installation location from `$HOME` to `C:\Users\{username}\AppData\Local` (This is currently where Surrealist is installed).

### Alternative methods

N/A

### SurrealDB version

surreal 2.0.0 for windows 11

### Contact Details

matthewjnield@gmail.com

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by matthewjnield** [comment]
@Odonno Thanks for opening a pull request to address this. Let me know if I should close this issue in the `surrealdb` repository, and reopen it in the `windows.surrealdb.com` repository where the change would be made.

**Comment by Odonno** [comment]
No need to worry @matthewjnield. One of the member of the team will be able to move this issue to the right repository.
